# Generated by Django 4.1.7 on 2023-03-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('message', models.TextField(max_length=1024, null=True, verbose_name='对话文本')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('detail', models.CharField(max_length=16, null=True, verbose_name='对话细节')),
                ('chatmessage', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='chatgpt.chatmessage', verbose_name='message_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
