# Generated by Django 4.1.7 on 2023-03-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbox',
            name='chatmessage',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chatbox',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='chatgpt.chatbox', verbose_name='box_id'),
            preserve_default=False,
        ),
    ]
