# Generated by Django 4.1.7 on 2023-03-25 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0002_remove_chatbox_chatmessage_chatmessage_chatbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d84015b6-64fe-49e2-8001-ac8e728d7356'), primary_key=True, serialize=False, verbose_name='主键id'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d84015b6-64fe-49e2-8001-ac8e728d7356'), primary_key=True, serialize=False, verbose_name='主键id'),
        ),
    ]
