# Generated by Django 4.1.7 on 2023-03-25 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0004_alter_chatbox_id_alter_chatmessage_chatbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
    ]
