# Generated by Django 4.1.7 on 2023-03-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0006_alter_chatmessage_chatbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(max_length=1024, null=True, verbose_name='响应文本'),
        ),
    ]
