# Generated by Django 4.1.7 on 2023-03-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0007_chatmessage_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.JSONField(max_length=1024, null=True, verbose_name='对话文本'),
        ),
    ]
